[tool.poetry]
name = "pondus"
version = "0.8.1+git"
description = ""
authors = ["Eike Nicklas <eike@ephys.de>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
PyGObject = "^3.38.0"
matplotlib = "^3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
