# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test and lint

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
          python-version: 3.9
    - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
    - name: Install dependencies
        run: poetry install --no-interaction --no-root
    - name: Install library
        run: poetry install --no-interaction
    - name: Test with pytest
      run: |
        source .venv/bin/activate
        pytest tests/
